- package.json
Previously, `yarn lint` only ran on .js and .vue files.  However, we should also run it on standalone typescript files.
> yarn lint should also look at .ts files

- .eslintrc
- package.json
- src/components/CatalogResults.vue
- src/interfaces/SearchResult.ts
- src/services/SearchService.ts
- yarn.lock
I noticed that eslint hasn't really been doing many checks of the typescript code, either in the services or the components.  This PR enables some more checks.
> More eslint checking for typescript

- src/config.ts
Sibling PR in princeton_ansible: https://github.com/pulibrary/princeton_ansible/pull/4414
Helps with #88
> prefix envvar with VITE_ to make it available to the browser

- src/fixtures/ArticleResultsFixtures.ts
- src/models/SearchResult.ts
This allows us to create test fixtures more easily, since we can just copy/paste the object from the API response
> Convenience API for creating new SearchResult objects

- src/components/TrayContainer.vue
Also adds min-height to the row, to make trays jump around a bit less when the data is loading.
closes #94
> Trays don't expand to fit the whole row height

- src/components/metadata/ArticlesMetadata.vue
- src/components/metadata/SearchMetadata.vue
- src/config/ItemTypeMap.ts
Currently, the "map" metadata is showing up in every tray
Also, make icon/format matching case-insensitive
> Fix duplicate metadata in catalog tray

- assets/app.css
- src/components/TrayContainer.vue
- src/components/metadata/SearchMetadata.vue
- src/config/ScopeFieldsMap.ts
- src/config/ScopeTitleMap.ts
- src/config/ScopeUrlMap.ts
closes #60 
Also includes a fix to an issue I noticed with VoiceOver, where empty metadata fields are still included in visually hidden text
> i60: FAQ tray

- index.html
Using a <meta> tag rather than an HTTP header,
since this application doesn't have an application server.
> Add Content Security Policy

- package.json
- src/components/JumpToSection.vue
- src/components/SearchBar.vue
- src/components/TrayContainer.vue
- yarn.lock
closes #148
- Add grey background in search bar and Skip to links
- Remove border from skip to links
- Include resolutions in package.json in order to resolve: node_modules/eslint/lib/cli-engine/formatters/stylish.js to a dynamic import() which is available in all CommonJS modules.
> Add grey background in search bar and Skip to links

- src/components/TrayTitle.vue
Tray title is not a link. It doesn't need to have focus.
> Remove focus from tray title

- src/components/TrayLayout.vue
Previously, in mobile screens, the full catalog and article trays would display prior to the data being loaded.  After the data is loaded, the catalog tray is almost always so big that it pushes the article tray below the fold in mobile views.  This layout shift could be annoying to users with slow connections who see articles momentarily, then it disappears.
Setting a reasonable min-height for each tray makes this layout shift less drastic, and brings the mobile CLS (as measured locally with Lighthouse using the search term "music") from .36 to .143.
helps with #155
> Reduce mobile layout shift

- src/components/BestBetsTray.test.ts
- src/components/BestBetsTray.vue
- src/components/TrayContainer.vue
- src/components/TrayLayout.vue
Previously, while the Best Bet tray was deciding whether or not to display, the first row showed two large columns, rather than three medium-sized ones.  This led to layout shift, once the third column shows up.
This brings the desktop CLS from .3 to .091
closes #155
> Reduce cumulative layout shift on desktop sizes

- assets/app.css
- src/components/InlineBadge.vue
- src/components/PhysicalHoldings.test.ts
- src/components/PhysicalHoldings.vue
- src/models/PhysicalHolding.test.ts
- src/models/PhysicalHolding.ts
- src/services/HoldingsService.test.ts
- src/services/HoldingsService.ts
This will display a status badge for all catalog items with physical holdings except Recap items, which will come in a separate PR.
Helps with #166
> Display status from other_fields in the API response

- .circleci/config.yml
When we added Dastardly in [this commit](https://github.com/pulibrary/allsearch_frontend/pull/178/files) the node version changed to 18.12
> Update node version to 18.18.0 in circleci config

- src/components/PhysicalHoldings.test.ts
- src/components/PhysicalHoldings.vue
- src/components/SearchTray.vue
- src/components/metadata/CatalogMetadata.test.ts
- src/components/metadata/CatalogMetadata.vue
Rather than parsing the entire search result document
Related to #166
> Refactor: CatalogMetadata only accepts the data it needs for display

- index.html
Currently it is being blocked, according to my firefox console:
```
Content-Security-Policy: The page’s settings blocked the loading of a resource at https://use.typekit.net/xbi8ees.css (“style-src”).
```
> Allow Adobe font in the Content Security Policy

- src/components/InlineBadge.vue
- src/components/PhysicalHoldings.test.ts
previously, when a status updated, the badge color did not also change, since the color was a const computed once when the component was created. Let's use a Vue computed property instead, so that the value can change as the holding status changes.
part of #166
> Always display correct colors for status badges

- src/components/InlineBadge.vue
- src/components/PhysicalHoldings.vue
* Adding status badges as a subsidiary list adds extra structure and verbosity needlessly.  Just add them to the main list
* The Available badge had insufficient contrast.
part of #166
> Accessibility improvements for status badges

- index.html
Closes #189
Note that you can also [report content-security-policy errors to Honeybadger](https://docs.honeybadger.io/guides/errors/#content-security-policy-reports), but they say it can be noisy, so it's good to have it use a different Honeybadger project.
> Add honeybadger to content security policy connect-src

- src/services/SearchService.test.ts
- src/services/SearchService.ts
> Catch axios promise rejections (caused by non-200 HTTP responses from the API)

- README.md
Small change that might make setup faster / easier for new devs, pointing out you need to be on VPN for most searches to work.
> Add note about being on VPN for development

- src/models/RecordHoldingsMap.test.ts
- src/models/RecordHoldingsMap.ts
Bibdata was returning 404 errors for requests to the SCSB availability API that didn't contain any SCSB barcodes.  This manifested as a CORS error in the browser console, since the 404 from the server didn't contain the CORS headers.
closes #234
> Don't check bibdata for SCSB availability unless there are SCSB holdings

- src/components/JumpToSection.vue
- src/components/TrayContainer.vue
closes #227
- Update skip to section links to be flex items
- Wrap them in two, three rows based on the media query 
- Wrap them and set flex item to take 100% of the basis when in mobile view.
> Update skip to section links to be flex items

- src/components/MoreResults.vue
closes #280 
on hover remove underline
change color ratio to pass AA normal text, 
display the entire label on a single line
Remove box shadow since we have the full button change to orange on hover.
> Update refine button

- src/components/TrayContainer.test.ts
- src/components/TrayContainer.vue
Currently, we jump directly to H2 headings.  This PR adds a visually hidden H1 heading at the top of the search results.
> Add H1 to search results page

- src/components/BestBetsTray.vue
- src/components/MoreResults.vue
- src/components/SearchTray.vue
- src/components/TrayContainer.vue
- src/components/TrayLayout.vue
- src/components/TrayTitle.vue
closes #257
supports screens:  (min-width: 1281px) and (max-width: 2089px)
Update tray grid to use flex and not arrays per column/row
screens: @media (min-width: 1281px) and (max-width: 2089px)
Remove shadow from tray; Increase line-height in titles for better readability;
Update refine results link to look like a link with bold font;
Underline main tray title description with orange-50;
Use gray to devide list of books in a tray;
Add light gray background color in middle trays;
Update color in best-bets; Add padding in best bets and tray-grid
> Update tray grid to use flex and not arrays per column/row

- .vscode/extensions.json
Some of the extensions previously in this file were deprecated.
> Update extension recommendations

- src/App.vue
part of #313 
Add max-width in .main;
Align flex items: center in page-wrap
The old all search supports max-width: 1200px
The new library website supports 1440px;
The new all search will support max-width: 1440px
> [#313] Move Footer and Header outside of page-wrap; update flex and max-width

- src/components/JumpToSection.vue
part of #313 
Remove unnecessary padding; 
Remove unnecessary flex assignment on jump-to-section element;
Align quick links with the search form and the tray grid;
> Update Quick links alignment

- assets/app.css
- src/App.vue
Add left and right margin in page-wrap class.
It was causing extra whitespace around the header and the footer.
> Remove margin from skip-to-content-links.

- src/App.vue
#351 started to use the header component from lux, but unfortunately, this also caused the Skip to Main link to be hidden behind the header.
This places the Skip to Main link over the Header when active, and makes the position consistent with what it was prior to #351.
Helps with #316
> Make Skip to Content visible on top of the lux header

- src/App.vue
This makes the left spacing consistent with the lux header and footer (which both have a padding of `1rem`, allowing the trays and logos to be aligned horizontally with each other.
helps with #316
> [#316] use a consistent amount of spacing on the left

- package.json
- yarn.lock
closes #316 , since this version of Lux has the same spacing in the header and footer.
> Bump lux version to 5.2.13

- src/components/metadata/LibraryStaffMetadata.test.ts
- src/components/metadata/LibraryStaffMetadata.vue
closes #380 
The tray contains Staff member's name, library title and email.
Remove office, building and phone number
> [#380] Add library_title. Remove office, building and phone number

- package.json
- src/App.vue
- src/main.ts
- yarn.lock
It needs https://github.com/pulibrary/lux-design-system/pull/297
closes #384
Import lux style.css first so that we can override specific lux styles if desired
Opening this as a draft until https://github.com/pulibrary/lux-design-system/pull/297 is merged
> [#384] Support Dark system mode for the disclosure icon

- package.json
- src/components/BannerAlert.test.ts
- src/components/BannerAlert.vue
- yarn.lock
We use localStorage to remember that a user has dismissed the banner. As long as the text doesn't change, we won't display the banner again for another week.
closes #391
> [#391] Remember when the user has dismissed the banner

- src/components/MoreResults.vue
part of #400 
Use href text in <a> tag. Remove span
Remove text-decoration from more-link let it take the default underline decoration
from the user agent.
> [#400] Updates on more-link 

- src/components/MoreResults.vue
closes #400 
Use border-bottom instead of text-decoration for a.more-link
Support hover in both light and dark theme
> [#400] [MoreResults] Remove space between the text and the icon

- README.md
Move the Vitest VScode Plugin and Integration/e2e tests, in the Running test section
> Update README: Git Hook section

- src/components/SearchBar.vue
closes #407 
I used the padding values from the catalog searchbar
> [#407] Add padding in the searchbar

- src/components/AppHeader.test.ts
- src/components/AppHeader.vue
- src/config/ScopeUrlMap.ts
As part of the website migration, the new WDS-managed website will stop being at library.psb-prod.princeton.edu and instead be at library.princeton.edu.
Most of these changes can be made in the API using the feature flipper (see https://github.com/pulibrary/allsearch_api?tab=readme-ov-file#use-the-permanent-website-url), but the header and the zero-results tray had the
temporary psb-prod url hard-coded.
> Remove hard-coded psb-prod URLs

- src/components/metadata/LibraryStaffMetadata.test.ts
- src/components/metadata/LibraryStaffMetadata.vue
- src/fixtures/LibraryStaffResultsFixtures.ts
- tsconfig.json
Also, increase the lib version in tsconfig, so that we can use String.prototype.replaceAll()
They display underneath the job title, in parentheses (because I thought the parentheses looked nice).
closes #417
> [#417] Display pronouns if available from the API

- assets/app.css
- src/components/BestBetsTray.vue
- src/components/JumpToSection.vue
- src/components/SearchBar.vue
- src/components/TrayLayout.vue
- src/components/TrayTitle.vue
closes #422
Dark theme: Change the primary surface color to dark grey.
see material docs: https://m2.material.io/design/color/dark-theme.html#properties Remove tray border and support higher surface elevation for main tray components by providing a lighter shade of gray.
Change link color to light grey to support color contrast accessibility ratio.
> [#422] Color changes to support dark theme

- index.html
- src/config.ts
Rename bibdata-staging.princeton.edu to bibdata-staging.lib.princeton.edu
Bibdata staging is on adc-dev and using the .lib
> Rename bibdata-staging.princeton.edu to bibdata-staging.lib.princeton.edu

- assets/app.css
- src/App.vue
- src/components/BestBetsTray.vue
- src/components/JumpToSection.vue
- src/components/MoreResults.vue
- src/components/SearchBar.vue
- src/components/SearchTray.vue
- src/components/TrayContainer.vue
- src/components/TrayLayout.vue
- src/components/TrayTitle.vue
This is recommended by this article: https://css-tricks.com/come-to-the-light-dark-side/
Helps with #443
> Refactor light/dark mode to use CSS light-dark

- vite.config.ts
Helps with #444
One way you can validate this change:
1. `yarn build`
2. `cd dist && ruby -run -e httpd . -p 7878`
3. In firefox, go to http://localhost:7878/
4. Open the dev tools
5. Go to the sources tab
6. Note that in Main Thread > localhost:7878, there is a single assets/index* js file that is minified.
7. Check out this branch and repeat steps 1-5.
8. Note that in Main Thread > localhost:7878, we can still access the minified js file in assets, but we also have the original typescript available in src.
> Configure vite to output sourcemaps

- src/components/SearchTray.vue
Update li.document spacing/display
*  display as flex
* Set flex settings
Update metadata class
* use padding-bottom for access-info
* Remove unneeded margin
* Remove padding from li
part of #506
> Metadata spacing

- src/config.ts
This will allow CI to actually get some results, and developers will not need to be on the VPN to get results.
> [main] Use the production API for local dev and CI

- src/config.ts
This will allow CI to actually get some results, and developers will not need to be on the VPN to get results.
> [branch] Use the production API for local dev and CI

- package.json
- src/components/SearchTray.vue
- src/components/metadata/ArticlesMetadata.test.ts
- src/components/metadata/ArticlesMetadata.vue
- src/fixtures/ArticleResultsFixtures.ts
- yarn.lock
Abstracts longer than 100 characters are truncated, and we get a Show abstract link
Helps with #508
> [ArticleMetadata] Use LuxShowMore for long abstracts

- assets/app.css
- src/components/SearchTray.vue
This prevents us from shifting the layout when tabbing or moving the mouse between titles
> Consistent line height on search result titles across states

- src/components/JumpToSection.vue
Jump to results is now in line with Catalog, Articles+, etc.
Closes #581
> [JumpToSection] Horizontally align Jump to results button with its contents
