pulibrary/allsearch_frontend

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/maintenance_task.md
- .github/ISSUE_TEMPLATE/new_component.md
A starting place. Feedback on the new_component template definitely welcome. For #5.
> Add issue templates.

- .circleci/config.yml
- .vscode/extensions.json
- README.md
- package.json
- src/components/__tests__/sum.test.js
- yarn.lock
> Add Vitest with example test and CircleCI

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/production.rb
- config/deploy/staging.rb
> Deployment with capistrano

- src/components/HelloWorld.test.ts
Also use typescript for our initial test example.
> Interfile tests with the code that they test

- src/enums/SearchScope.ts
- src/interfaces/SearchResult.ts
- src/interfaces/SearchResults.ts
- src/services/SearchService.test.ts
- src/services/SearchService.ts
> Add fake data service

- package.json
- yarn.lock
This will allow us to test the output of our components
> Add vue test-utils

- src/components/SearchBar.vue
- src/services/SearchTermService.test.ts
- src/services/SearchTermService.ts
Thanks @rladdusaw for the tip about making it static.
> Refactor getting Search Term from query into its own service

- .circleci/config.yml
- public/assets/styles/app.css
- src/App.vue
- src/components/CatalogResults.test.ts
- src/components/CatalogResults.vue
- src/components/FormatWithIcon.test.ts
- src/components/FormatWithIcon.vue
- src/components/OnlineContent.test.ts
- src/components/OnlineContent.vue
- src/components/PhysicalHoldings.test.ts
- src/components/PhysicalHoldings.vue
- src/interfaces/SearchResult.ts
- src/services/SearchService.ts
> i20 catalog search

- .circleci/config.yml
- README.md
> Add semgrep to CircleCI

- src/App.test.ts
- src/App.vue
- src/components/AppHeader.vue
> Add skip navigation link

- src/components/CatalogResults.vue
- src/components/MoreResults.vue
- src/components/TrayTitle.test.ts
- src/components/TrayTitle.vue
> Refactor some HTML and styles into their own components

- src/main.ts
> Remove honeybadger test notification

- public/assets/styles/app.css
- src/App.vue
- src/components/ArticleCitation.test.ts
- src/components/ArticleCitation.vue
- src/components/ArticleResults.test.ts
- src/components/ArticleResults.vue
- src/components/CatalogResults.vue
- src/components/FormatWithIcon.test.ts
- src/components/FormatWithIcon.vue
- src/components/InlineBadge.vue
- src/components/OnlineContent.vue
- src/components/TrayLayout.vue
- src/components/TrayTitle.vue
- src/enums/SearchScope.ts
- src/interfaces/SearchResult.ts
> i33 articles tray

- .circleci/config.yml
- .rspec
- Gemfile
- Gemfile.lock
- README.md
- index.html
- spec/page_title_spec.rb
- spec/spec_helper.rb
- src/App.vue
Includes rspec integration tests, since this couldn't be tested via unit tests.
closes #50
> Meaningful page title

- public/assets/styles/app.css
- src/App.vue
- src/components/ArticleResults.vue
- src/components/CatalogResults.vue
- src/components/FindingaidsResults.test.ts
- src/components/FindingaidsResults.vue
- src/components/FormatWithIcon.vue
- src/components/TrayLayout.vue
- src/fixtures/FindingAidsResultsFixtures.ts
> i34: add a findingaids tray

- public/assets/styles/app.css
- src/App.vue
- src/components/FindingaidsResults.test.ts
- src/components/PulMapResults.test.ts
- src/components/PulMapResults.vue
- src/fixtures/PulMapResultsFixtures.ts
> Add PulMap tray component

- spec/search_spec.rb
- spec/spec_helper.rb
- src/App.vue
- src/components/InitialSearch.test.ts
- src/components/InitialSearch.vue
- src/components/SearchBar.test.ts
- src/components/SearchBar.vue
- src/components/WarningAlert.vue
> i74: search form does not allow empty searches

- public/assets/styles/app.css
- src/components/TrayContainer.vue
- src/components/metadata/DpulMetadata.test.ts
- src/components/metadata/DpulMetadata.vue
- src/components/metadata/SearchMetadata.vue
- src/config/ItemTypeMap.ts
- src/config/ScopeTitleMap.ts
- src/config/ScopeUrlMap.ts
- src/fixtures/DpulResultsFixtures.ts
closes #56 
Deployed to staging on 20 October
> i56: add a DPUL tray

- src/components/TrayContainer.vue
- src/components/metadata/ArtMuseumMetadata.test.ts
- src/components/metadata/ArtMuseumMetadata.vue
- src/components/metadata/SearchMetadata.test.ts
- src/components/metadata/SearchMetadata.vue
- src/config/ScopeTitleMap.ts
- src/config/ScopeUrlMap.ts
- src/fixtures/ArtmuseumResultsFixtures.ts
closes #57 
Deployed to staging on 20 October
> i57: Add art museum tray

- public/assets/styles/app.css
- src/components/TrayContainer.vue
- src/components/metadata/ArticlesMetadata.vue
- src/components/metadata/CatalogMetadata.vue
- src/components/metadata/DpulMetadata.vue
- src/components/metadata/PulmapsMetadata.vue
- src/components/metadata/SearchMetadata.test.ts
- src/components/metadata/SearchMetadata.vue
- src/config/ScopeFieldsMap.ts
- src/config/ScopeTitleMap.ts
- src/config/ScopeUrlMap.ts
- src/fixtures/LibguidesResultsFixtures.ts
> Add libguides tray

- assets/app.css
- src/components/BestBetsTray.test.ts
- src/components/BestBetsTray.vue
- src/components/TrayContainer.vue
- src/config/ScopeFieldsMap.ts
- src/config/ScopeTitleMap.ts
- src/fixtures/BestBetResultsFixture.ts
> i61: best bets

- assets/app.css
- src/components/TrayContainer.vue
- src/components/TrayLayout.vue
- src/components/metadata/ArtMuseumMetadata.test.ts
- src/components/metadata/SearchMetadata.test.ts
- src/config/ScopeFieldsMap.ts
- src/config/ScopeTitleMap.ts
- src/config/ScopeUrlMap.ts
- src/fixtures/LibraryDatabasesResultsFixtures.ts
> i58: library databases tray

- docs/new_tray.md
> Add docs for creating a new tray

- assets/app.css
- src/components/InlineBadge.vue
> Adjust text spacing, especially in the metadata display

- src/components/SearchTray.vue
> i125: don't indent list contents

- src/components/metadata/FindingaidsMetadata.test.ts
- src/components/metadata/FindingaidsMetadata.vue
- src/components/metadata/SearchMetadata.test.ts
- src/components/metadata/SearchMetadata.vue
- src/services/StringService.test.ts
- src/services/StringService.ts
> i128: truncate long descriptions

- src/components/SearchTray.vue
> i132: title underlines turn orange on hover and focus

- assets/app.css
- src/components/MoreResults.vue
closes #129 
Asked aux for review on 26 October.
> i129: view and refine link: make it a button on focus/hover

- src/components/ArticleResults.test.ts
- src/components/FindingaidsResults.test.ts
- src/components/PulMapResults.test.ts
- src/components/SearchTray.vue
- src/components/TrayContainer.vue
- src/config/ScopeIconMap.ts
> Refactor tray defaultIcon prop into a map

- src/components/BestBetsTray.test.ts
- src/components/BestBetsTray.vue
- src/components/SearchTray.test.ts
- src/components/SearchTray.vue
- src/components/TrayContainer.vue
- src/components/TrayTitle.test.ts
- src/components/TrayTitle.vue
- src/interfaces/SearchDataLoadSummary.ts
- src/models/TrayOrder.test.ts
- src/models/TrayOrder.ts
- src/services/IdService.test.ts
- src/services/IdService.ts
* Refactor TrayContainer to read Column/Row order from a class
* Emit event when each tray has finished loading its data, so that the TrayContainer component can determine the correct order
* Add ids to trays (in preparation for JumpToSection links)
closes #134
> i134: Show best bets only if there is content

- src/components/JumpToSection.test.ts
- src/components/JumpToSection.vue
- src/components/TrayContainer.vue
- src/components/TrayTitle.vue
> i32 jump to section

- src/components/TrayContainer.vue
- src/components/TrayLayout.vue
> i131: increase tray width

- src/components/AppHeader.vue
- src/components/TrayContainer.vue
In lighthouse diagnostics, it appears to be the 'Largest Contentful Paint element 410 ms'
> remove - coming soon

- .eslintignore
- src/components/SearchBar.test.ts
- src/components/SearchBar.vue
Closes #137. SearchBar.vue is ignored by eslint to pass tests.
> Fix alignment

- index.html
> Rel preconnect

- src/components/PhysicalHoldings.test.ts
- yarn.lock
Needed to change one test to avoid checking the
amount of whitespace in a wrapper's text(), due
to https://github.com/vuejs/test-utils/pull/2231.
> Upgrade @vue/test-utils to 2.4.2

- src/components/SearchTray.vue
- src/components/TrayLayout.vue
> Add loading for trays

- assets/app.css
- docs/new_tray.md
- src/components/metadata/SearchMetadata.vue
- src/components/metadata/WebsiteMetadata.vue
- src/config/ScopeFieldsMap.ts
- src/config/ScopeIconMap.ts
- src/config/ScopeTitleMap.ts
- src/config/ScopeUrlMap.ts
- src/enums/SearchScope.ts
- src/models/TrayOrder.ts
> Added website tray

- assets/app.css
- docs/new_tray.md
- src/components/metadata/LibraryStaffMetadata.test.ts
- src/components/metadata/LibraryStaffMetadata.vue
- src/components/metadata/SearchMetadata.test.ts
- src/components/metadata/SearchMetadata.vue
- src/config/ScopeFieldsMap.ts
- src/config/ScopeIconMap.ts
- src/config/ScopeTitleMap.ts
- src/config/ScopeUrlMap.ts
- src/enums/SearchScope.ts
- src/fixtures/LibraryStaffResultsFixtures.ts
- src/models/TrayOrder.ts
> i63: add Library Staff Tray

- assets/app.css
closes #151
using the [Option 1 Use font-display](https://web.dev/articles/avoid-invisible-text#option_1_use_font-display)
> Avoid invisible text during font loading-use font-display: swap; #151

- assets/app.css
- src/components/AppHeader.vue
- src/components/InlineBadge.vue
- src/components/MoreResults.vue
- src/components/SearchBar.vue
- src/components/SearchTray.vue
- src/components/TrayLayout.vue
> Add WDS styleguide colors as CSS variables

- assets/app.css
- src/components/FormatWithIcon.vue
- src/components/MoreResults.vue
- src/components/SearchTray.vue
- src/components/TrayLayout.vue
- src/components/TrayTitle.vue
- src/components/metadata/SearchMetadata.vue
> Implement tray styling based on the WDS style guide

- assets/app.css
> Use the font recommended by the WDS style guide

- src/components/PhysicalHoldings.test.ts
- src/components/PhysicalHoldings.vue
- src/components/metadata/CatalogMetadata.vue
- src/fixtures/CatalogMetadataFixtures.ts
- src/fixtures/SearchServiceFixtures.ts
- src/services/HoldingsService.test.ts
- src/services/HoldingsService.ts
> Display two holdings in catalog tray

- src/components/AppFooter.vue
- src/components/AppHeader.vue
> Adjust footer styling for desktop view part of#203

- src/components/JumpToSection.vue
- src/components/SearchBar.vue
> 182 search form styles

- src/components/AppFooter.vue
> Add footer mobile view for sizes greater than 440px and less than 820px

- src/components/OnlineContent.test.ts
- src/components/OnlineContent.vue
- src/components/SearchTray.vue
- src/components/metadata/CatalogMetadata.test.ts
- src/components/metadata/CatalogMetadata.vue
> i224: Display url label as link text, if available from the API

- assets/app.css
- src/components/InlineBadge.vue
- src/components/OnlineContent.vue
- src/components/metadata/ArticlesMetadata.vue
> Blue online content badges

- src/components/AppFooter.vue
- src/components/SubscribeNewsletter.test.ts
- src/components/SubscribeNewsletter.vue
> Add Subscribe button

- index.html
> Allow img-src self data in CSP

- src/components/AppFooter.vue
- src/components/AppHeader.vue
> Resolve Files in the public directory are served at the root path warning

- .circleci/config.yml
- .tool-versions
Sibling PR: https://github.com/pulibrary/princeton_ansible/pull/4667
> Node 20.11.1

- src/components/AppFooter.vue
- src/components/SubscribeNewsletter.vue
> Add styles for the subscribe newsletter button and input part of #203

- package.json
- yarn.lock
See [eslint-plugin-vuejs-accessibility#924](https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility/issues/924)
> Update eslint-plugin-vuejs-accessibility. 

- .eslintrc
- src/components/AppFooter.vue
- src/components/AppHeader.vue
closes #203 
[Header] Add mobile view. 
[Header] Adjust flex for desktop view.
> [Header] Update Desktop and Add Mobile view 

- docs/new_tray.md
- src/components/SearchTray.vue
- src/config/ScopeFieldsMap.ts
- src/config/ScopeIconMap.ts
- src/config/ScopeTitleMap.ts
- src/config/ScopeUrlMap.ts
- src/enums/SearchScope.ts
- src/models/TrayOrder.ts
Closes #256 
I put it in a somewhat random location, since we are going to reorganize the layout of various trays anyway.
> Add journal tray

- src/App.vue
- src/components/JumpToSection.vue
- src/components/SearchBar.vue
- src/components/TrayContainer.vue
part of #227 
Remove unneeded flex property align-items in searchbar using flex
Remove flex from elements that is not needed
> Update search form and skip to section. 

- src/components/AppFooter.vue
- src/components/SearchBar.vue
- src/components/TrayContainer.vue
> Update nav.search-tools to grow and shrink from a flex basis of auto

- src/components/JumpToSection.vue
> Add trayArray function to flatten trayOrder skip to section links

- src/components/BestBetsTray.test.ts
- src/components/BestBetsTray.vue
- src/components/TrayContainer.vue
- src/config/ScopeFieldsMap.ts
- src/config/ScopeIconMap.ts
- src/config/ScopeTitleMap.ts
- src/enums/SearchScope.ts
- src/models/TrayOrder.test.ts
- src/models/TrayOrder.ts
> 187 move best bets

- src/App.vue
- src/components/AppHeader.vue
> Use the same orange color and underline text for all links

- .github/ISSUE_TEMPLATE/accessibility.md
- .github/ISSUE_TEMPLATE/accessibility_audit.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/dependency_upgrade.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/maintenance-task.md
- .github/ISSUE_TEMPLATE/maintenance_task.md
- .github/ISSUE_TEMPLATE/ui-change.md
Connected to pulibrary/dacs_handbook#170
> Align with team issue templates

- src/components/JumpToSection.vue
towards #274 
Remove underline text, 
Highlight the entire button on hover 
on hover update background color to var(--orange-50) and foreground color var(--gray-90)
> Remove underline text, Highlight the entire button on hover, on hove

- src/components/JumpToSection.vue
> centered text, add pointer towards #274

- src/components/JumpToSection.vue
> Add padding to the skip to section a tag to move content to the center

- src/components/JumpToSection.vue
> Skip to section- center the a tag href content

- src/components/SearchTray.test.ts
- src/components/SearchTray.vue
- src/components/TrayTitle.vue
- src/config/ScopeDescriptionMap.ts
> Added tray descriptions

- spec/skip_to_main_spec.rb
- src/App.vue
- src/components/AppHeader.vue
- yarn.lock
Closes #275
Used [Vue Accessibility best-practices documents](https://vuejs.org/guide/best-practices/accessibility#skip-link) as a reference for this PR.
> Make skip to main content link only visible when focused

- .gitignore
- package.json
- src/components/metadata/ArticlesMetadata.vue
- src/main.ts
- yarn.lock
> Add an abstract disclosure widget using lux

- src/components/JumpToSection.test.ts
- src/components/JumpToSection.vue
- src/components/TrayContainer.vue
- src/models/TrayOrder.test.ts
- src/models/TrayOrder.ts
> Show all JumpToSection links without waiting for data load

- src/components/PhysicalHoldings.vue
- src/components/SearchTray.vue
- src/components/metadata/ArticlesMetadata.vue
> Fix nested list

- src/components/TrayContainer.vue
> Update media query to min 1024px

- index.html
> Add google tag manager script

- src/components/MoreResults.test.ts
- src/components/MoreResults.vue
- src/components/SearchTray.test.ts
- src/components/SearchTray.vue
> [#312] Don't include a number of results in library database tray

- package.json
- yarn.lock
part of https://github.com/pulibrary/allsearch_frontend/issues/313
> Update Lux to 5.2.2

- src/components/JumpToSection.vue
closes #321 
part of https://github.com/pulibrary/allsearch_frontend/issues/313
> [Skip to Section] Update ul li a with flex: 1 1 auto

- index.html
- src/components/SearchBar.vue
Resolves #244
Added dark mode support to the index.html meta tags and using the @media (prefers-color-schem: dark) media query to apply border color changes when using dark mode to browse.
> Added dark mode support and setting border color

- index.html
- package.json
- src/main.ts
- yarn.lock
- Update content security policies
This sends data from my local and staging to google analytics. See [realtime dashboard](https://analytics.google.com/analytics/web/?authuser=0#/p447803729/realtime/overview?params=_u..nav%3Dmaui&collectionId=business-objectives)
> Try manual GA install again

- src/App.vue
> Remove bottom-padding from .main

- src/components/TrayContainer.vue
part of #313 
Align tray-grid with search-bar form
> Align tray-grid with search-bar

- src/components/TrayContainer.vue
part of #313
[Tray-grid] - Media query support @media (max-width: 1199px) for bottom 6 trays ;
[Tray-grid] Media support @media (min-width: 900px) for top 6 trays;
> [Tray Grid] Media query support  max-width: 1199px, min-width: 900px

- src/App.vue
- src/components/JumpToSection.vue
> [#313] media query support for Skip to Section; Set max-width in media queries in .main

- src/components/TrayContainer.vue
> [#313] [TrayContainer] Support trays across various media queries

- src/App.vue
I forgot to commit these changes in the [previous PR](https://github.com/pulibrary/allsearch_frontend/pull/345)
> Add margin tray container

- package.json
- yarn.lock
See lux release 5.2.6 notes: https://github.com/pulibrary/lux-design-system/releases/tag/v5.2.6
> Update lux version to 5.2.6

- package.json
- yarn.lock
See release notes: https://github.com/pulibrary/lux-design-system/releases/tag/v5.2.7
> Update lux to 5.2.7

- package.json
- yarn.lock
Release notes: https://github.com/pulibrary/lux-design-system/releases/tag/v5.2.8
> Update lux to 5.2.8

- package.json
- yarn.lock
See release notes: https://github.com/pulibrary/lux-design-system/releases/tag/v5.2.9
> Update lux to 5.2.9

- src/App.vue
- src/components/AppHeader.vue
> [#316] Use LuxLibraryHeader

- package.json
- yarn.lock
Release notes: https://github.com/pulibrary/lux-design-system/releases
> Update Lux to 5.2.11

- src/components/SearchBar.vue
> [#313] Fixes Search Bar responsiveness in small screens - UI was tested in 305px

- package.json
- yarn.lock
See release notes: https://github.com/pulibrary/lux-design-system/releases/tag/v5.2.12
> Update lux to 5.2.12

- src/components/TrayContainer.vue
- src/models/TrayOrder.test.ts
- src/models/TrayOrder.ts
> [#25] Reorder Trays to have the desired display -  Structure one row to use in the tray layout

- src/components/FindingaidsResults.test.ts
- src/components/PulMapResults.test.ts
- src/components/SearchTray.vue
> [#279] update language for zero results

- src/components/BestBetsTray.vue
> [#360] Remove description Lorum Ipsum from Best Bets Tray

- package.json
- yarn.lock
Release notes: https://github.com/pulibrary/lux-design-system/releases/tag/v5.2.14
> Update lux to 5.2.14

- assets/app.css
- src/App.vue
- src/components/MoreResults.vue
- src/components/SearchTray.vue
- src/components/TrayContainer.vue
- src/components/TrayLayout.vue
- src/components/TrayTitle.vue
Wrote dark mode media queries for Axe DevTools accessibility tests to pass. Closes #344.
> 344 dark mode tray contents

- spec/jump_to_section_spec.rb
- src/components/JumpToSection.vue
> 342 toggle skip to section

- src/config/ScopeTitleMap.ts
> Update staff title to Staff Directory

- src/components/BestBetsTray.test.ts
- src/components/BestBetsTray.vue
- src/fixtures/BestBetResultsFixture.ts
> [#367] display full description for Best Bets

- src/components/SearchTray.test.ts
- src/components/SearchTray.vue
- src/components/TrayLayout.test.ts
> Include aria-label for sections

- src/components/AppHeader.vue
> [#371] Update application title to All Search

- src/components/BestBetsTray.vue
> [#383] Dark mode background color for best bets tray

- src/App.vue
- src/components/BannerAlert.test.ts
- src/components/BannerAlert.vue
- src/components/TrayContainer.vue
- src/interfaces/Banner.ts
- src/models/BannerResult.ts
- src/services/BannerService.ts
> Add banner component

- src/App.vue
- src/components/SearchTray.vue
> Match lux focus for links

- src/config/ScopeDescriptionMap.ts
> Remove duplicate description

- src/components/MoreResults.vue
> Update border-bottom in dark and light mode

- package.json
- src/App.vue
- yarn.lock
See release notes: https://github.com/pulibrary/lux-design-system/releases/tag/v5.3.1 
Add padding-bottom to the .page-wrap
> Update lux version to v5.3.1

- package.json
- yarn.lock
Release notes: https://github.com/pulibrary/lux-design-system/releases/tag/v5.3.3
> Update Lux to 5.3.3

- package.json
- yarn.lock
Release notes: https://github.com/pulibrary/lux-design-system/releases/tag/v5.5.1
> Update Lux to v5.5.1

- package.json
- yarn.lock
Release notes: https://github.com/pulibrary/lux-design-system/releases/tag/v5.6.2
> Update Lux to 5.6.2 - Updates Footer - New website Library links 

- src/config/ScopeUrlMap.ts
- src/fixtures/LibraryStaffResultsFixtures.ts
> Update staff url

- package.json
- src/components/AppHeader.vue
- yarn.lock
Update this Pr with the new Lux version
> Add and set abbrName prop for LuxLibraryHeader

- package.json
- yarn.lock
Release notes: https://github.com/pulibrary/lux-design-system/releases/tag/v5.7.1
> Update Lux to 5.7.1

- package.json
- yarn.lock
Release notes: https://github.com/pulibrary/lux-design-system/releases/tag/v5.8.1
> Update lux to 5.8.1

- package.json
- src/App.vue
- src/components/AppHeader.test.ts
- src/components/AppHeader.vue
- yarn.lock
> Add a light-mode/dark-mode switcher

- index.html
Some more adjustments for tag manager to pass through CSP.
> Tag manager needs additional CSP adjustments.

- spec/accessibility_spec.rb
- src/components/JumpToSection.vue
Also, fix a color contrast issue so the test passes
> Add a dark mode accessibility test

- package.json
- yarn.lock
https://github.com/pulibrary/lux-design-system/releases/tag/v6.1.4 
https://github.com/pulibrary/lux-design-system/releases/tag/v6.1.5 
https://github.com/pulibrary/lux-design-system/releases/tag/v6.1.6
> Update to lux 6.1.6

- package.json
- yarn.lock
For solving issues related to [https://github.com/pulibrary/lux-design-system/issues/429](url)
> Updates lux to newest version 6.3.1

- .circleci/config.yml
part of https://github.com/pulibrary/allsearch_frontend/issues/460
> Update circleci version to 23.11.0

- README.md
For issue https://github.com/pulibrary/allsearch_frontend/issues/466.
> Add lux dependency to project readme.

- package.json
- vite.config.ts
- yarn.lock
Based on the documentation here: https://github.com/honeybadger-io/honeybadger-js/tree/master/packages/rollup-plugin
Closes #444
> Send sourcemaps to honeybadger

- assets/app.css
- package.json
- src/App.vue
- src/components/TrayLayout.vue
- src/components/TrayTitle.vue
- yarn.lock
Updates spacing of page-wrap class - helps with #501
Remove tray border
* part of #502
> Updates spacing of page-wrap class - helps with #501

- src/components/TrayLayout.vue
> Tray spacing

- assets/app.css
- src/components/ArticleResults.test.ts
- src/components/BestBetsTray.test.ts
- src/components/FindingaidsResults.test.ts
- src/components/PulMapResults.test.ts
- src/components/SearchTray.test.ts
- src/components/TrayTitle.test.ts
- src/components/TrayTitle.vue
- src/config/ScopeDescriptionMap.ts
- Font size update
- Remove icons before tray titles
- Update tray descriptions
Connected to #502
> Update tray heading to match Figma more closely

- src/components/TrayContainer.vue
> I deleted accidentally the . from the class

- package.json
- spec/search_spec.rb
- src/components/SearchBar.test.ts
- src/components/SearchBar.vue
- src/main.ts
- yarn.lock
Helps with #497
feedback from AUX has been incorporated.
> [main] Use LuxSearchBox, rather than our own styles, for the search box

- src/components/JumpToSection.vue
* Remove % size of flex item in specific screen sizes
* Keep only quick links 100% in a size less than 833px
* update gap in quick links flex box
> Update quick-links display

- src/components/MoreResults.vue
> Update view and refine option

- src/App.vue
This is an incremental step to reorganizing the structure of the page, while keeping every element within an aria landmark.
> Add Skip to Main link to a nav

- src/components/SearchTools.vue
Update <nav class="search-tools">
* Make nav class="search-tools" a flexbox
* Give flex-direction: column and center align the flex items
> Nav search tools flex

- spec/jump_to_section_spec.rb
- src/components/JumpToSection.vue
Connected to #537 
Still need to figure out how to make it be on a white background on small screens and a black background on large screens.
> Incremental progress on mobile jump-to-section

- src/components/FindingaidsResults.test.ts
- src/components/metadata/FindingaidsMetadata.vue
> [FindingaidsMetadata] do not display repository

- src/components/metadata/FindingaidsMetadata.test.ts
- src/components/metadata/FindingaidsMetadata.vue
> [FindingaidsMetadata] Add show more for the abstract

- src/components/TrayContainer.vue
- src/components/TrayLayout.vue
- src/models/TrayOrder.test.ts
- src/models/TrayOrder.ts
Update layout section.
step 1:
helps with #501
> 501 page layout v1

- src/components/JumpToSection.vue
> 537 new mobile menu

- assets/app.css
- src/components/InlineBadge.vue
- src/components/OnlineContent.test.ts
- src/components/OnlineContent.vue
- src/components/PhysicalHoldings.test.ts
- src/components/PhysicalHoldings.vue
- src/components/SearchTray.vue
- src/components/TrayLayout.vue
- src/components/metadata/CatalogMetadata.test.ts
- src/components/metadata/CatalogMetadata.vue
- src/components/metadata/FindingaidsMetadata.test.ts
- src/models/PhysicalHolding.test.ts
- src/models/PhysicalHolding.ts
> Restyle catalog metadata

- src/components/SearchTools.vue
> Add some padding to SearchTools for mobile only

- assets/app.css
- src/components/FormatWithIcon.vue
- src/components/TrayTitle.vue
- src/components/metadata/SearchMetadata.vue
> 580 font adjustment

- assets/app.css
- src/components/TrayLayout.vue
- src/components/metadata/LibraryStaffMetadata.vue
> Adjust font size

- src/components/TrayLayout.vue
- src/components/metadata/ArticlesMetadata.vue
- src/components/metadata/DpulMetadata.vue
> Adjust fonts

- src/components/FindingaidsResults.test.ts
- src/components/metadata/FindingaidsMetadata.vue
> [FindingaidsMetadata] remove date

- src/components/JumpToSection.vue
display flex where needed
part of #599
> Add media queries for jump to section link.

- src/components/TrayLayout.vue
- src/components/TrayTitle.vue
> [TrayLayout] Fix wrong css property name

- src/components/SearchTray.vue
> Make titles in the tray orange

- src/components/SearchTray.vue
This reverts commit 08e543907dc55266e7bdafa219662717d0adf518.
> Revert "Make titles in the tray orange"

- src/components/metadata/ArticlesMetadata.vue
> 609 articles publisher font size

- src/components/TrayTitle.vue
> Remove extra padding when tray description is empty

- src/components/MoreHelpResults.vue
- src/components/SearchTray.vue
> 585 document spacing

- src/components/BestBetsTray.test.ts
- src/components/BestBetsTray.vue
> [#621] Fix regression in Best bet links

- index.html
Fixes local analytics for allsearch.
> Allow Umami to send fetch requests.
